### ISSUE TITLE
IncidenceRate SQL Server - SQL Error

### ISSUE THREAD

**Issue by shorban-uod** [ohdsi-studies/Covid19SubjectsAesiIncidenceRate#14]
Covid19SubjectsAesiIncidenceRate v1.2.4 completes the cohort creation and cohort diagnostics successfully, but fails at the first incidence rate SQL query on a Microsoft SQL Server database.

I have been unable to run the SQL on SQL Server Management Studio to debug, as it references temp tables which are cleared when the query fails.

Error and log files attached.

[errorReportSql.txt](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/files/7728185/errorReportSql.txt)
[Covid19SubjectsAesiIncidenceRate_ErrorReportR.txt](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/files/7728188/Covid19SubjectsAesiIncidenceRate_ErrorReportR.txt)
[Covid19SubjectsAesiIncidenceRate_log.txt](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/files/7728190/Covid19SubjectsAesiIncidenceRate_log.txt)
.

**Comment by ericaVoss** [comment]
I see the issue and I caused the problem.  I had a typo in my SQL and you must have pulled before I was able to fix it:
https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/commit/e49b85ff1553cbb70eeda582338560f01d5d2f39

You are bombing here:
`  CAST(count_big(distinct t1.subject_id) as num_persons_w_no_tar`

So you have 2 options:

### OPTION 1 - try to pick up where you bombed

- Keep your old run folder somewhere and create a new folder where you will run from
- In your new run folder run Step 2 again from the [How to run](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate#how-to-run)
- Move the results folder you have from your old run folder, this would have been what you defined as the output folder in the previous run
- In that old results folder, make sure the drop the incidenceRate folder
- Perform Step 4 again from the  [How to run](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate#how-to-run) EXCEPT:
```
createCohortsAndRef = FALSE,
runCohortDiagnostics = FALSE,
```
It should pick up again from the incidence rate

### OPTION 2 - start over

However, you can just start over again from a clean folder if you don't want to be bothered with the above.

**Comment by shorban-uod** [comment]
This has now been fixed and the issue I was running into was some sort of hangover from a previous install. Erica and I created a fresh folder, downloaded the lockfile and restored the project and this pulled the correct SQL file and solved the issue.

I'll close this issue now.
