### ISSUE TITLE
IR Results - Small Number Suppression Issue

### ISSUE THREAD

**Issue by shorban-uod** [ohdsi-studies/Covid19SubjectsAesiIncidenceRate#19]
The Incidence Rate results appear to have small number suppression disabled for columns O and P, ‘num_persons_pre_exclude’ and ‘num_persons_at_risk’. Other columns beginning with 'num_persons' **do** have small number suppression enabled though.

![image](https://user-images.githubusercontent.com/67638363/148973844-9a506f99-7a40-4205-a89b-81597c49715a.png)

@ericaVoss @msuchard

**Comment by shorban-uod** [comment]
I should also mention that the threshold value for the other columns is 5, so numbers smaller than that are shown as '-5'.

However I have not set this value explicitly in the CodeToRun.R script like I have for other studies.

**Comment by ericaVoss** [comment]
@shorban-uod - yeah, this package didn't expose setting the min cell count size.  It is getting set within the package.  We could have exposed it but just didn't here.  

I have a fix in, just running a test locally.

**Comment by ericaVoss** [comment]
I got it working, will commit it all to master soon.  Added two more columns for censorship:
~~~
"numPersonsPreExclude","numPersonsAtRisk"
~~~

![image](https://user-images.githubusercontent.com/6305439/149190918-873088b7-cecc-4dca-be5b-9ca38ebd0f7e.png)

**Comment by ericaVoss** [comment]
@shorban-uod I will also writer a scrubber for any results I already have.

**Comment by shorban-uod** [comment]
Will download, install and re-run the new package overnight :)
