### ISSUE TITLE
Multiple row entries in incidenceAnalysis

### ISSUE THREAD

**Issue by anthonysena** [ohdsi-studies/Covid19SubjectsAesiIncidenceRate#28]
In review from ETHON, there are data partners that have multiple duplicate rows in the `incidenceAnalysis`. The bug may be in the way that we are truncating the table prior to each IR run (it may be skipped) and/or that there is something wrong in the way that we're writing the results to CSV incrementally.

**Comment by ericaVoss** [comment]
- [x] @yampeku (Diego/FIIBAP)
- [x] MDM

**Comment by anthonysena** [comment]
Related to #18: The R function `createCohortsAndRef` is currently responsible for creating the "reference" tables but it also creates the IR summary table [here](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/blob/master/inst/sql/sql_server/CreateRefTables.sql#L49-L78). 

If someone chooses to use the `execute` function of the package with the following parameters:

```r
createCohortsAndRef = FALSE,
runCohortDiagnostics = FALSE,
runIR = TRUE
```

The process will skip re-creating the IR summary table and append the results to the existing table since the [runIncidenceAnalysis.sql](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/blob/master/inst/sql/sql_server/runIncidenceAnalysis.sql) does not clear that table at the moment.

**Comment by ericaVoss** [comment]
Reopening to ensure the issue fixes for the DP

**Comment by ericaVoss** [comment]
@yampeku - if I were you, I would just run from a clean folder and rerun the whole thing.  

Make sure the the version of the package you get is V1.2.7.
![image](https://user-images.githubusercontent.com/6305439/151712710-01f833cb-a5c2-4ef0-8a29-76c7ce3a4a07.png)


I sometimes run these first just to double make sure the old package is gone:
```
#renv::deactivate()
#remove.packages("Covid19SubjectsAesiIncidenceRate")
#renv::purge("Covid19SubjectsAesiIncidenceRate")
```
