### ISSUE TITLE
UK Biobank ETL Patch & Rerun

### ISSUE THREAD

**Issue by ericaVoss** [ohdsi-studies/Covid19SubjectsAesiIncidenceRate#39]
we have found a coding issue that will require the UK Biobank ETL to be patched and rerun

**Comment by ericaVoss** [comment]
> Thanks to the amazing hard work of the Hyve team, the new ETL version is currently running. If everything will go smoothly (fingers crossed), we should be able to deliver the updated AESI study results by the beginning of the next week. I hope it is still ok. Once this is done, I’d kindly ask you if we could schedule another meeting regarding the Censorship. - Vaclav

**Comment by ericaVoss** [comment]
Martijn/Sena/Gowtham/JPG, 

Hoping I could ask for some help, Vaclav is rerunning the COVID AESI study after updating the UK Biobank CDM.  But we are hitting a snag, and I’m not 100% sure what is going on.

Vaclav sent me this note:
“When I initiated and restore the environment as you described below, it crashes on incompatibility of Andromeda versions (there is version 0.5.0 in the study environment and it says the version 0.6.0. is required). However, after updating to version 0.6.0 another error occurs (about some styling). I’ve attached a log. Do you have any idea what could cause this?”

Here is my renv:
https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/blob/master/renv.lock#L14

Looks like it is dying in Feature Extraction on something called a clii__container_start(app, "span", class = funname)

Maybe a fresh install of Andromeda or does this spark any other ideas on your side?
https://ohdsi.github.io/Andromeda/#installation

My only other thought is the renv isn’t properly activated if it is looking for 0.6.0 for Andromeda.

Thank you,
Erica A. Voss

**Comment by azimov** [comment]
The CLI error has me a little stumped as I've not seen it before. I'm also not sure why the Andromeda version would be a problem, CohortDiagnostics and FeatureExtraction don't specify a version so the one stated shouldn't create an error.

I do note that the snapshot here uses CohortDiagnostics 2.2.0, there have been a few hot fixes (some are to do with compatibility of newer versions of dplyr) so it may be that upgrading the renv snapshot to 2.2.4 resolves this issue. I foresee no problems upgrading andromeda here too but @anthonysena might know better if this will create problems with FeatureExtraction.

**Comment by ericaVoss** [comment]
Received and uploaded the new data
