### ISSUE TITLE
Windows Drive Limit

### ISSUE THREAD

**Issue by ericaVoss** [ohdsi-studies/Covid19SubjectsAesiIncidenceRate#4]
I hit the usual obscure issue when I tried to run from a shared folder and the filename exceeded Windows’ internal limit, which threw some unhelpful errors, but I have fixed that by running from the C: drive. 

Add note in ReadMe

**Comment by schuemie** [comment]
I'm unfamiliar with this issue. Could you tell me more? Maybe we could bake something in to the HADES packages to prevent/warn about this.

**Comment by ericaVoss** [comment]
If you have the package too deep into a Windows file structure it throws an error like this.

I think there is a limit of 260 characters in Win10.
