### ISSUE TITLE
Don't call preMergeDiagnosticsFiles

### ISSUE THREAD

**Issue by schuemie** [ohdsi-studies/Covid19SubjectsAesiIncidenceRate#5]
Study packages should not call `preMergeDiagnosticsFiles`, but this study package calls it [here](https://github.com/ohdsi-studies/Covid19SubjectsAesiIncidenceRate/blob/master/R/Main.R#L110). The output of this function is a binary file, and therefore does not meet our definitions for transparency about what is shared. Instead, just share the zipped csv files, and call `preMergeDiagnosticsFiles` at the study coordinating site (where it can be run across the output of all data partners).

(A nice added benefit is that it avoids [this issue](https://github.com/OHDSI/CohortDiagnostics/issues/702), which could then be worked around at the central site by editing the CSV file)

**Comment by ericaVoss** [comment]
See, this is what I get for not listening to you
